using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml;
using System.Xml.Linq;

namespace RssFeedReaderv1._0
{
    public partial class MainWindow : Form
    {

        //private DataGridView dataGridView1 = new DataGridView();
        private BindingSource bindingSource1 = new BindingSource();
        private SqlDataAdapter dataAdapter = new SqlDataAdapter();
        public MainWindow()
        {
            InitializeComponent();
            //getRssFeedFileUrl("http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml");
            // This line of code is generated by Data Source Configuration Wizard
        }

        public void getRssFeedFileUrl(string url)
        {
            WebRequest request = WebRequest.Create(url);
            WebResponse response = request.GetResponse();
            Stream rssStream = response.GetResponseStream();
            XmlDocument xmlDoc = new XmlDocument();
            xmlDoc.Load(rssStream);
            XmlNodeList xmlNodeList = xmlDoc.SelectNodes("//rss/channel/item");

            try
            {
                SqlConnection conn = new SqlConnection(@"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Alala\documents\visual studio 2017\Projects\RssFeedReaderv1.0\RssFeedReaderv1.0\App_Data\Database.mdf;Integrated Security=True");
                
                string insert_query = "insert into [ItemsNews] (title,content,link) values (@title,@content,@link)";

                //using (var context = new DatabaseEntities1())

                //var p = context.links.OrderByDescending(c => c.Id).FirstOrDefault();
                //int newId = (null == p ? 0 : p.Id) + 1;
                //link l = new link()
                //{

                //    Id = newId,
                //    link1 = url
                //};
                //context.links.Add(l);
                //context.SaveChanges();
                //string s=xmlNodeList.Item(0).SelectSingleNode("title").InnerText;
                //string ss = xmlNodeList.Item(0).SelectSingleNode("description").InnerText;
                string Itemcontent=null;
                string Itemtitle = null;
                for (int i = 0; i < xmlNodeList.Count; i++)
                {
                    //XmlNode xmlNode;
                    //var item = new Item()
                    //{
                    conn.Open();
                    Itemtitle = xmlNodeList.Item(i).SelectSingleNode("title").InnerText;
                    Itemcontent = xmlNodeList.Item(i).SelectSingleNode("description").InnerText;
                    SqlCommand cmd = new SqlCommand(insert_query, conn);
                    cmd.Parameters.AddWithValue("@link", txtboxRsslink.Text);
                    cmd.Parameters.AddWithValue("@title", Itemtitle);
                    cmd.Parameters.AddWithValue("@content", Itemcontent);
                    cmd.ExecuteNonQuery();
                    conn.Close();
                    //};
                    //link.Items.Add(item);

                    //Console.WriteLine(.InnerText);
                    //xmlNode = xmlNodeList.Item(i).SelectSingleNode("ProductName");
                    //xmlNode.InnerText;
                }

                
            }
            catch (Exception ex)
            {
                Console.Write("ERORR:" + ex.ToString());
            }
            //    //link = context.rsslinks.Add(link);
            //    context.SaveChanges();

           // gridControl2.Refresh();
        }

        private void GetData(string selectCommand)
        {
            try
            {
                // Specify a connection string.  
                // Replace <SQL Server> with the SQL Server for your Northwind sample database.
                // Replace "Integrated Security=True" with user login information if necessary.
                String connectionString =@"Data Source = (LocalDB)\MSSQLLocalDB; AttachDbFilename = C:\Users\Alala\documents\visual studio 2017\Projects\RssFeedReaderv1.0\RssFeedReaderv1.0\App_Data\Database.mdf; Integrated Security = True";

                // Create a new data adapter based on the specified query.
                dataAdapter = new SqlDataAdapter(selectCommand, connectionString);

                // Create a command builder to generate SQL update, insert, and
                // delete commands based on selectCommand. 
                SqlCommandBuilder commandBuilder = new SqlCommandBuilder(dataAdapter);

                // Populate a new data table and bind it to the BindingSource.
                DataTable table = new DataTable
                {
                    Locale = CultureInfo.InvariantCulture
                };
                dataAdapter.Fill(table);
                bindingSource1.DataSource = table;

                // Resize the DataGridView columns to fit the newly loaded content.
                dataGridView1.AutoResizeColumns(
                    DataGridViewAutoSizeColumnsMode.AllCellsExceptHeader);
            }
            catch (SqlException)
            {
                MessageBox.Show("To run this example, replace the value of the " +
                    "connectionString variable with a connection string that is " +
                    "valid for your system.");
            }
        }

        private void MainWindow_Load(object sender, EventArgs e)
        {
            dataGridView1.DataSource = bindingSource1;
            GetData("select * from ItemsNews");
            // TODO: This line of code loads data into the 'databaseDataSet.ItemsNews' table. You can move, or remove it, as needed.

            // TODO: This line of code loads data into the 'databaseDataSet1.ItemsNews' table. You can move, or remove it, as needed.

            // TODO: This line of code loads data into the 'databaseDataSet.ItemsNews' table. You can move, or remove it, as needed.

            // TODO: This line of code loads data into the 'dBMDFDataSet.rsslink' table. You can move, or remove it, as needed.
            // TODO: This line of code loads data into the 'dBDataSet.rsslink' table. You can move, or remove it, as needed.

        }

        private void add_Click(object sender, EventArgs e)
        {
            try
            {
                getRssFeedFileUrl(txtboxRsslink.Text);
                GetData(dataAdapter.SelectCommand.CommandText);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.StackTrace);
            }
        }

        private void gridControl2_Click(object sender, EventArgs e)
        {

        }
    }
}
